### ISSUE TITLE
fix(npm): fix preinstall script preventing package installation

### ISSUE THREAD

**Issue by Firkraag** [beatrizsmerino/vue-todolist#437]
# fix(npm): fix preinstall script preventing package installation

| ⏱️ Estimate | 📊 Priority | 📏 Size | 📅 Start | 📅 End |
|---------|-------------|---------|----------|--------|
| 2h      | P1          | S       | 25-10-2023 | 22-11-2023 |

## 📝 Summary

- Running `npm install` does not install packages correctly because the `preinstall` script runs `npm install --package-lock-only`, which skips the actual installation and jumps directly to `postinstall`
- This causes a cascade of errors including a 404 for `@vue/vue-loader-v15` and a missing module `svg-symbol-sprite-loader`

## 💡 Why this bug?

- The `preinstall` script in `package.json` contains `npm install --package-lock-only`, which only generates/updates the `package-lock.json` file without actually installing packages to `node_modules`
- After `preinstall` completes, npm considers the install phase done and moves directly to `postinstall`, skipping the actual dependency installation
- This means `node_modules` is never properly populated

## ✅ Expected behavior

- Running `npm install` should install all dependencies into `node_modules`
- The `preinstall` script should not interfere with the main installation process
- All packages should be available after installation

## 📋 Steps

- [x] Remove or fix the `--package-lock-only` flag from the `preinstall` script in `package.json`
- [x] If the `preinstall` script is not needed, remove it entirely
- [x] Run `npm install` to verify packages install correctly
- [x] Verify the application builds and runs

## 🧪 Tests

- [x] `npm install` completes without errors
- [x] All packages are installed in `node_modules`
- [x] No 404 errors for `@vue/vue-loader-v15`
- [x] `svg-symbol-sprite-loader` module is found
- [x] Application builds and runs successfully

### Files modified

- [x] `package.json` (preinstall script)

**Comment by Firkraag** [comment]
The node version is v20.9.0, the npm version is 10.1.0

**Comment by beatrizsmerino** [comment]
I will try to install the packages with your `node 20` and `npm 10` versions and see what happens.

![Captura de pantalla 2023-10-26 a las 21 48 47](https://github.com/beatrizsmerino/vue-todolist/assets/14045148/6a10c85a-5afd-409f-94d6-474aeda9a6da)

**Comment by beatrizsmerino** [comment]
During the installation process:
1. The `install:clean` command removes the `node_modules` directory and the `package-lock.json` file.
2. The `dependencies:fix` command updates or creates the `package-lock.json` without touching the `node_modules` directory without running any scripts, and uses `npm-force-resolutions` to force the dependency versions as specified in the `resolutions` field of your `package.json`.

So removing `--package-lock-only` would complicate the process and make it less efficient, as you would be doing a full install of the dependencies, only to potentially have to do it again after forcing resolutions. 
This means that after removing the `node_modules` and `package-lock.json` in the `install:clean` step, it will immediately attempt to reinstall all dependencies. Depending on the size of your project, this could slow down the process considerably.
Using `--package-lock-only` in your current flow ensures a cleaner and more optimized process.


I don't know why in `node 14` and `npm 6` version if it is working fine, I have to investigate this a little more.

**Comment by Firkraag** [comment]
node 14 and npm 6 works
<img width="976" alt="image" src="https://github.com/beatrizsmerino/vue-todolist/assets/4558542/1c94a9a6-a392-4022-b971-c75a96d81121">

**Comment by beatrizsmerino** [comment]
Ok thank you very much for the help, I will try to adapt the project to the next versions of `node` and `npm` as soon as I have a moment.

**Comment by beatrizsmerino** [comment]
In `hotfix/3.3.3` the project can now:
- Be installed and run if `node@14` is used.
- It no longer uses `Volta` but `nvm`.
- In the `package.json` and `.nvmrc` you can see the required version of node

6520cc8881d81a77bffe5369fa6fbee688a7704c

**Comment by beatrizsmerino** [comment]
⚠️ Support for `node@20` in version `3.3.4`
